import type { CustomerCatalogItem } from "./catalog";

export const sampleCatalog: CustomerCatalogItem[] = [
  {
    id: "bolt-2xm-nm-nonfoil",
    name: "Lightning Bolt",
    setCode: "2XM",
    setName: "Double Masters",
    collectorNumber: "129",
    printing: "nonfoil",
    condition: "NM",
    rarity: "uncommon",
    colors: ["R"],
    cardType: "Instant",
    manaValue: 1,
    pricePhp: 120,
    stock: 4,
    imageUrl: "https://cards.scryfall.io/normal/front/1/1/110a8c0f-10d1-4d84-8d11-7a0518a3d0e0.jpg",
    dateAdded: "2026-05-10"
  },
  {
    id: "bolt-clu-lp-foil",
    name: "Lightning Bolt",
    setCode: "CLU",
    setName: "Ravnica Clue Edition",
    collectorNumber: "141",
    printing: "foil",
    condition: "LP",
    rarity: "rare",
    colors: ["R"],
    cardType: "Instant",
    manaValue: 1,
    pricePhp: 260,
    stock: 1,
    imageUrl: "https://cards.scryfall.io/normal/front/1/1/110a8c0f-10d1-4d84-8d11-7a0518a3d0e0.jpg",
    dateAdded: "2026-05-12"
  },
  {
    id: "sol-ring-ltc-nm-nonfoil",
    name: "Sol Ring",
    setCode: "LTC",
    setName: "The Lord of the Rings Commander",
    collectorNumber: "284",
    printing: "nonfoil",
    condition: "NM",
    rarity: "uncommon",
    colors: [],
    cardType: "Artifact",
    manaValue: 1,
    pricePhp: 80,
    stock: 0,
    imageUrl: "https://cards.scryfall.io/normal/front/6/0/60b7e2a4-638a-4d1e-88c4-947b253a722a.jpg",
    dateAdded: "2026-05-08"
  },
  {
    id: "atraxa-one-mp-nonfoil",
    name: "Atraxa, Grand Unifier",
    setCode: "ONE",
    setName: "Phyrexia: All Will Be One",
    collectorNumber: "196",
    printing: "nonfoil",
    condition: "MP",
    rarity: "mythic",
    colors: ["W", "U", "B", "G"],
    cardType: "Legendary Creature",
    manaValue: 7,
    pricePhp: 910,
    stock: 2,
    imageUrl: "https://cards.scryfall.io/normal/front/3/7/37f16637-7f32-4f22-8e40-6f6b3dfadbea.jpg",
    dateAdded: "2026-05-14"
  }
];
